# test004

In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [4]:
def arange_metrix(row, col):
    return np.arange(row*col).reshape(row, col)

In [3]:
a1 = np.arange(12).reshape(3,4)
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [8]:
a1[2, 3], a1[2][3]

(11, 11)

In [13]:
a1[2], a1.T[2], a1[:, 2], a1[2, :]

(array([ 8,  9, 10, 11]),
 array([ 2,  6, 10]),
 array([ 2,  6, 10]),
 array([ 8,  9, 10, 11]))

In [15]:
index = np.indices((2,2))
a1[index]

array([[[[0, 1, 2, 3],
         [0, 1, 2, 3]],

        [[4, 5, 6, 7],
         [4, 5, 6, 7]]],


       [[[0, 1, 2, 3],
         [4, 5, 6, 7]],

        [[0, 1, 2, 3],
         [4, 5, 6, 7]]]])

In [16]:
a1[1, 1:3]

array([5, 6])

In [17]:
a1[-2]

array([4, 5, 6, 7])

In [18]:
a1[a1<10]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
a1<10

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False]])

In [24]:
a2 = np.zeros_like(a1)
a2[1:] = 1
a2

array([[0, 0, 0, 0],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [26]:
a2.astype(np.bool_())

array([[False, False, False, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [25]:
a1[a2.astype(np.bool_())]

array([ 4,  5,  6,  7,  8,  9, 10, 11])

In [28]:
a1, a1[1, 0:4:2]

(array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([4, 6]))

In [31]:
a1[2,3] = 100
a1[a1<10] = 10
a1

array([[ 10,  10,  10,  10],
       [ 10,  10,  10,  10],
       [ 10,  10,  10, 100]])

In [34]:
a1[a1<11],a1

(array([10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10]),
 array([[ 10,  10,  10,  10],
        [ 10,  10,  10,  10],
        [ 10,  10,  10, 100]]))

## numpy合并

In [70]:
b1 = np.arange(6).reshape(2,3)
b2 = np.zeros((2,3))
b1,b2

(array([[0, 1, 2],
        [3, 4, 5]]),
 array([[0., 0., 0.],
        [0., 0., 0.]]))

In [39]:
np.vstack([b1,b2])

array([[0., 1., 2.],
       [3., 4., 5.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [40]:
np.hstack([b1,b2])

array([[0., 1., 2., 0., 0., 0.],
       [3., 4., 5., 0., 0., 0.]])

In [42]:
np.concatenate([b1,b2], axis=1)

array([[0., 1., 2., 0., 0., 0.],
       [3., 4., 5., 0., 0., 0.]])

## 查询

In [58]:
indices = np.where((b1<5)&(b1>2))
indices

(array([1, 1], dtype=int64), array([0, 1], dtype=int64))

In [59]:
indices_x, indices_y = indices
b1[indices_x,indices_y]

array([3, 4])

In [61]:
type(b1)

numpy.ndarray

In [62]:
np.take(b1, indices)

array([[1, 1],
       [0, 1]])

## 其他

In [66]:
a = np.arange(5)
b = a
a, b, a is b

(array([0, 1, 2, 3, 4]), array([0, 1, 2, 3, 4]), True)

In [65]:
b[0]=100
a, b

(array([100,   1,   2,   3,   4]), array([100,   1,   2,   3,   4]))

In [67]:
b = a.copy()
b[1] = 100
a, b, a is b

(array([0, 1, 2, 3, 4]), array([  0, 100,   2,   3,   4]), False)

In [82]:
a4 = np.random.randn(5,10)
np.vstack(np.meshgrid(np.arange(5),np.arange(10))).reshape(2,-1).T

array([[0, 0],
       [1, 0],
       [2, 0],
       [3, 0],
       [4, 0],
       [0, 1],
       [1, 1],
       [2, 1],
       [3, 1],
       [4, 1],
       [0, 2],
       [1, 2],
       [2, 2],
       [3, 2],
       [4, 2],
       [0, 3],
       [1, 3],
       [2, 3],
       [3, 3],
       [4, 3],
       [0, 4],
       [1, 4],
       [2, 4],
       [3, 4],
       [4, 4],
       [0, 5],
       [1, 5],
       [2, 5],
       [3, 5],
       [4, 5],
       [0, 6],
       [1, 6],
       [2, 6],
       [3, 6],
       [4, 6],
       [0, 7],
       [1, 7],
       [2, 7],
       [3, 7],
       [4, 7],
       [0, 8],
       [1, 8],
       [2, 8],
       [3, 8],
       [4, 8],
       [0, 9],
       [1, 9],
       [2, 9],
       [3, 9],
       [4, 9]])

## 数组统计函数

In [83]:
a5 = np.random.rand(100)-0.5

In [86]:
a5.mean(), np.median(a5), np.percentile(a5,0.5)

(0.014833379567794673, 0.020789200933701457, -0.486185010968833)

In [88]:
a5.std(), a5.var(), a5.std()**2

(0.2853458407259949, 0.08142224881962486, 0.08142224881962484)

In [92]:
a5.min(), a5.max(), np.argmax(a5), np.argmin(a5), a5[np.argmax(a5)]

(-0.495419466443061, 0.4998768024820096, 53, 57, 0.4998768024820096)

In [99]:
a5.sum(), a5.reshape(2,-1).sum(), a5.reshape(2, -1).sum(axis=1)

(1.4833379567794673, 1.4833379567794673, array([-0.32971946,  1.81305741]))

In [100]:
a5.prod()

-1.2920967641069092e-72

In [101]:
np.all(a5<0.5), np.any(a5<-0.49)

(True, True)

In [103]:
a5, np.sort(a5), np.argsort(a5)

(array([-0.23985018,  0.17610891,  0.45634118,  0.43925389,  0.15026175,
         0.15643728,  0.08180987,  0.23817544, -0.41946194,  0.16220075,
        -0.04480238, -0.15823512, -0.23214504, -0.43401666,  0.22050852,
        -0.3772422 , -0.25105091, -0.05759074,  0.39355026, -0.08995858,
        -0.12905963, -0.09315894,  0.23458459,  0.36329298,  0.4295217 ,
         0.09669326, -0.24448923, -0.40337187, -0.16257113, -0.00208339,
        -0.23125808,  0.00245192, -0.32556047, -0.40931859,  0.2254422 ,
         0.14378904,  0.22759067,  0.43388626,  0.13029933,  0.48393622,
         0.1529784 , -0.13891162, -0.24234079, -0.476764  , -0.38576934,
        -0.36571985,  0.30089018, -0.30127896, -0.03244513,  0.21873074,
         0.11667783, -0.08446116,  0.48960613,  0.4998768 , -0.29914503,
         0.27970778,  0.08354288, -0.49541947, -0.09874243,  0.23293972,
        -0.10261317, -0.43253614,  0.19774978,  0.07851323, -0.47183461,
         0.1872285 , -0.05681388,  0.33698543,  0.4

In [108]:
a6 = np.random.randint(0,10,20)
np.unique(a6), np.bincount(a6)

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([1, 3, 3, 2, 2, 1, 2, 2, 3, 1], dtype=int64))

In [114]:
a6 = np.linspace(1,16,16).reshape(4,4)
b6 = np.random.rand(4, 20)
np.linalg.inv(a6), np.dot(a6,b6), b6.T, np.transpose(b6)

(array([[ 1.50119988e+15, -3.75299969e+14, -3.75299969e+15,
          2.62709978e+15],
        [-1.95155984e+16,  1.95155984e+16,  1.95155984e+16,
         -1.95155984e+16],
        [ 3.45275971e+16, -3.79052969e+16, -2.77721977e+16,
          3.11498974e+16],
        [-1.65131986e+16,  1.87649984e+16,  1.20095990e+16,
         -1.42613988e+16]]),
 array([[ 3.20152092,  2.85152805,  5.90317898,  3.62616232,  4.09472719,
          3.2359051 ,  3.49963618,  3.10106188,  4.2844146 ,  6.88630124,
          2.03091466,  4.43106022,  4.01086904,  4.12173413,  5.52985496,
          6.04850351,  5.03460777,  4.36857944,  3.85407874,  2.35877294],
        [ 9.89388013,  9.63230822, 14.91543526,  9.7603006 , 11.78852399,
          7.87844309, 10.18738542,  8.05356849, 12.39060396, 16.47424627,
          5.76367417, 11.16373807, 11.06852663, 12.25162978, 14.57008459,
         15.706497  , 12.21555214, 12.01786182,  8.31681177,  7.7104051 ],
        [16.58623933, 16.41308839, 23.92769155, 15.89443

## 练习

In [7]:
t1a = np.zeros(8)
t1b = np.ones(8)
t1c = np.vstack([t1a,t1b])
t1c.T.reshape(4,4)

array([[0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.]])

In [ ]:
np.where(a>0.5)

In [8]:
t2 = np.random.rand(5)
t2[np.argsort(t2)]

array([0.17475824, 0.21047631, 0.22774576, 0.26408778, 0.72047021])

In [9]:
t3x,t3y = np.meshgrid(np.arange(10),np.arange(10))
t3x, t3y

(array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]]),
 array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
        [3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
        [4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
        [5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
        [6, 6, 6, 6, 6, 6, 6, 6, 6, 6],
        [7, 7, 7, 7, 7, 7, 7, 7, 7, 7],
        [8, 8, 8, 8, 8, 8, 8, 8, 8, 8],
        [9, 9, 9, 9, 9, 9, 9, 9, 9, 9]]))

In [10]:
(t3x**2 + t3y**2)**0.5

array([[ 0.        ,  1.        ,  2.        ,  3.        ,  4.        ,
         5.        ,  6.        ,  7.        ,  8.        ,  9.        ],
       [ 1.        ,  1.41421356,  2.23606798,  3.16227766,  4.12310563,
         5.09901951,  6.08276253,  7.07106781,  8.06225775,  9.05538514],
       [ 2.        ,  2.23606798,  2.82842712,  3.60555128,  4.47213595,
         5.38516481,  6.32455532,  7.28010989,  8.24621125,  9.21954446],
       [ 3.        ,  3.16227766,  3.60555128,  4.24264069,  5.        ,
         5.83095189,  6.70820393,  7.61577311,  8.54400375,  9.48683298],
       [ 4.        ,  4.12310563,  4.47213595,  5.        ,  5.65685425,
         6.40312424,  7.21110255,  8.06225775,  8.94427191,  9.8488578 ],
       [ 5.        ,  5.09901951,  5.38516481,  5.83095189,  6.40312424,
         7.07106781,  7.81024968,  8.60232527,  9.43398113, 10.29563014],
       [ 6.        ,  6.08276253,  6.32455532,  6.70820393,  7.21110255,
         7.81024968,  8.48528137,  9.21954446

In [11]:
t3x,t3y = np.meshgrid(np.arange(4)**2,np.arange(4)**2)
t3x,t3y

(array([[0, 1, 4, 9],
        [0, 1, 4, 9],
        [0, 1, 4, 9],
        [0, 1, 4, 9]]),
 array([[0, 0, 0, 0],
        [1, 1, 1, 1],
        [4, 4, 4, 4],
        [9, 9, 9, 9]]))

In [22]:
t4 = np.meshgrid(np.arange(10), np.zeros(3), np.ones(5))
t4a, t4b, t4c = t4
t4a = t4a.reshape(-1)
t4b = t4b.reshape(-1)
t4c = t4c.reshape(-1)
np.vstack([t4a,t4b,t4c]).T

array([[0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 1.],
       [1., 0., 1.],
       [1., 0., 1.],
       [1., 0., 1.],
       [1., 0., 1.],
       [2., 0., 1.],
       [2., 0., 1.],
       [2., 0., 1.],
       [2., 0., 1.],
       [2., 0., 1.],
       [3., 0., 1.],
       [3., 0., 1.],
       [3., 0., 1.],
       [3., 0., 1.],
       [3., 0., 1.],
       [4., 0., 1.],
       [4., 0., 1.],
       [4., 0., 1.],
       [4., 0., 1.],
       [4., 0., 1.],
       [5., 0., 1.],
       [5., 0., 1.],
       [5., 0., 1.],
       [5., 0., 1.],
       [5., 0., 1.],
       [6., 0., 1.],
       [6., 0., 1.],
       [6., 0., 1.],
       [6., 0., 1.],
       [6., 0., 1.],
       [7., 0., 1.],
       [7., 0., 1.],
       [7., 0., 1.],
       [7., 0., 1.],
       [7., 0., 1.],
       [8., 0., 1.],
       [8., 0., 1.],
       [8., 0., 1.],
       [8., 0., 1.],
       [8., 0., 1.],
       [9., 0., 1.],
       [9., 0., 1.],
       [9., 0

In [23]:
np.vstack(np.meshgrid(np.arange(10), np.zeros(3), np.ones(5))).reshape(3,-1).T


array([[0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 1.],
       [1., 0., 1.],
       [1., 0., 1.],
       [1., 0., 1.],
       [1., 0., 1.],
       [2., 0., 1.],
       [2., 0., 1.],
       [2., 0., 1.],
       [2., 0., 1.],
       [2., 0., 1.],
       [3., 0., 1.],
       [3., 0., 1.],
       [3., 0., 1.],
       [3., 0., 1.],
       [3., 0., 1.],
       [4., 0., 1.],
       [4., 0., 1.],
       [4., 0., 1.],
       [4., 0., 1.],
       [4., 0., 1.],
       [5., 0., 1.],
       [5., 0., 1.],
       [5., 0., 1.],
       [5., 0., 1.],
       [5., 0., 1.],
       [6., 0., 1.],
       [6., 0., 1.],
       [6., 0., 1.],
       [6., 0., 1.],
       [6., 0., 1.],
       [7., 0., 1.],
       [7., 0., 1.],
       [7., 0., 1.],
       [7., 0., 1.],
       [7., 0., 1.],
       [8., 0., 1.],
       [8., 0., 1.],
       [8., 0., 1.],
       [8., 0., 1.],
       [8., 0., 1.],
       [9., 0., 1.],
       [9., 0., 1.],
       [9., 0

In [ ]:
np.cross()
np.multiply()

In [44]:
t4 = np.random.randint(0,100,size=(10,25))
t4

array([[14, 47, 61, 33,  9, 56, 85, 42, 66, 92, 39, 67, 98, 35, 47, 54,
        61, 40, 30, 77, 33, 65, 72, 60, 26],
       [58, 18, 67,  4, 15, 73, 33, 68, 78, 84, 39, 37, 52, 20, 28, 43,
        25, 50,  4, 13, 85, 75, 44, 61, 75],
       [42, 26, 93, 52, 95, 59, 76, 88, 57,  2, 65, 29, 58, 83, 48, 20,
         3, 15, 65, 59, 39, 35, 81, 22, 33],
       [75, 34, 62, 89,  4, 60, 20, 37, 44, 47, 63,  6, 56, 35, 34, 27,
         3, 99, 85, 64,  1,  0, 94, 24, 51],
       [28, 89, 11, 59, 10, 37, 49, 54, 11, 64, 45, 29, 77, 16, 29, 92,
        66, 57, 15, 70, 65, 16, 47,  6, 50],
       [95, 12, 80, 69,  1, 21,  4, 30, 51, 88, 25, 95, 26, 65, 36,  8,
        58, 97, 60, 90, 32, 32, 24, 90, 21],
       [51, 17,  2, 94,  1, 36, 90, 96, 79, 42, 33, 86, 94, 62, 59,  6,
        61, 35, 61, 96, 42, 67, 34, 10, 28],
       [24,  3, 34, 47, 95, 12, 31, 86, 73, 72, 37, 61, 10, 12, 69, 55,
        73, 55, 80, 17, 59, 63, 98, 88, 47],
       [93, 82, 24, 36, 98, 87, 36, 18, 35, 54, 95, 19, 75, 74, 

In [29]:
t4.shape[1]

5

In [46]:
def conv_mean(array):
    shape = array.shape
    index_list = np.vstack(np.meshgrid(np.arange(shape[0]-2), np.arange(shape[1]-2))).reshape(2,-1).T + 1
    outputarray = np.empty((shape[0]-2)*(shape[1]-2))
    for idx, i in enumerate(index_list):
        outputarray[idx] = np.sum(array[i[0]-1:i[0]+1, i[1]-1:i[1]+1] * 1/9)
    outputarray = outputarray.reshape(np.array(shape)-2)
    return outputarray

conv_mean(t4)

array([[15.22222222, 16.        , 19.66666667, 25.11111111, 24.88888889,
        19.44444444, 10.55555556, 22.44444444, 21.44444444, 22.66666667,
        23.88888889, 21.77777778, 21.33333333, 12.33333333,  6.22222222,
        15.88888889, 18.33333333, 24.        , 32.88888889, 24.55555556,
        24.33333333, 27.22222222, 19.66666667],
       [15.66666667,  6.77777778, 18.44444444, 26.66666667, 18.        ,
        15.44444444, 18.33333333, 26.33333333, 30.66666667, 17.        ,
        26.88888889, 24.22222222, 12.33333333,  7.66666667,  6.55555556,
        16.        , 32.44444444, 27.44444444, 26.77777778, 23.88888889,
        18.44444444, 12.33333333, 16.77777778],
       [18.77777778, 18.44444444, 25.33333333, 29.44444444, 24.55555556,
        17.77777778, 15.22222222, 24.44444444, 33.66666667, 19.        ,
        28.22222222, 32.33333333, 25.11111111, 16.22222222, 16.22222222,
        28.44444444, 37.11111111, 23.55555556, 35.55555556, 24.55555556,
        16.66666667, 18.4444

In [42]:
np.array(t4.shape)-2

array([3, 3])